mod address;
mod connection_id;
mod connection_pool;
mod connectors;
mod engine;
mod error;
mod file_watcher;
mod project_commands;
mod project_db_commands;
mod project_types;
mod variables;
mod window_manager;

use crate::connection_id::ConnectionRegistry;
use crate::file_watcher::{FileWatcherState, unwatch_project_config, watch_project_config};
use crate::project_commands::{
    delete_saved_query, get_saved_query, initialize_project, list_saved_queries,
    read_project_config, save_query, write_project_config,
};
use crate::project_db_commands::{
    close_connection, close_project_connections, connect_project_db, execute_raw_mongo,
    execute_raw_sql, get_connection_info, get_mongodb_collections, get_postgres_schemas,
    get_postgres_tables, get_sqlite_objects, query_mongodb_collection, query_postgres_table,
    query_sqlite_table,
};
use crate::window_manager::{close_window, focus_window, open_window};
use tauri::Manager;
use tauri_plugin_decorum::WebviewWindowExt;

/// Typescript exporter config shared between runtime dev-export and the
/// `export_bindings` test so the generated file is byte-identical.
fn ts_exporter() -> specta_typescript::Typescript {
    specta_typescript::Typescript::default()
        .header("// @ts-nocheck\n// Auto-generated by tauri-specta. Do not edit.\n")
        // DB row counts, limits, offsets use i64; JS `number` is accurate up to
        // 2^53-1 which is enough for our purposes.
        .bigint(specta_typescript::BigIntExportBehavior::Number)
}

/// Build the tauri-specta builder holding every typed command.
/// Kept as a separate function so tests / build scripts can export TS bindings
/// without spinning up Tauri's event loop.
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        // Canonical address types shared by every workspace-scoped
        // command. Exported even if no command currently references them
        // directly so the frontend can use them as the single source of
        // truth for "where am I looking" identifiers.
        .typ::<crate::address::ProjectAddress>()
        .typ::<crate::address::ConnectionAddress>()
        .typ::<crate::address::TabAddress>()
        .commands(tauri_specta::collect_commands![
            initialize_project,
            read_project_config,
            write_project_config,
            list_saved_queries,
            get_saved_query,
            save_query,
            delete_saved_query,
            watch_project_config,
            unwatch_project_config,
            connect_project_db,
            get_connection_info,
            get_sqlite_objects,
            get_mongodb_collections,
            get_postgres_schemas,
            get_postgres_tables,
            close_connection,
            close_project_connections,
            query_sqlite_table,
            query_postgres_table,
            query_mongodb_collection,
            execute_raw_sql,
            execute_raw_mongo,
            open_window,
            focus_window,
            close_window,
        ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let specta_builder = specta_builder();

    // Emit typed TS bindings during dev so the frontend has a single source of truth.
    #[cfg(debug_assertions)]
    specta_builder
        .export(ts_exporter(), "../src/bindings.ts")
        .expect("Failed to export typescript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_decorum::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);
            let main_window = app.get_webview_window("main").unwrap();
            main_window.create_overlay_titlebar().unwrap();

            #[cfg(target_os = "macos")]
            {
                main_window.set_traffic_lights_inset(16.0, 24.0).unwrap();
            }

            Ok(())
        })
        .manage(ConnectionRegistry::new())
        .manage(FileWatcherState::default())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod specta_export_tests {
    use super::*;

    /// Run `cargo test --lib -- export_bindings` to regenerate `src/bindings.ts`.
    /// Also runs automatically with the default `cargo test`, so CI keeps it fresh.
    #[test]
    fn export_bindings() {
        specta_builder()
            .export(ts_exporter(), "../src/bindings.ts")
            .expect("Failed to export typescript bindings");
    }
}
