schema_version = 1

name = "Base Collection Count"
description = "Total documents in the base collection"
tags = ["meta"]

[target]
connection = "public/watertap"

[aggregate]
collection = "base"
pipeline = """
[
  { "$count": "total" }
]
"""
