schema_version = 1

name = "List Collections"
description = "All collections in the EDB database"
tags = ["schema", "meta"]

[target]
connection = "public/watertap"

[aggregate]
pipeline = """
[
  { "$listCollections": {} },
  { "$project": { "name": 1, "type": 1 } },
  { "$sort": { "name": 1 } }
]
"""
