// @ts-nocheck
// Auto-generated by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Initialize a new Based project in the given directory
 */
async initializeProject(projectPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_project", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read and parse project config
 */
async readProjectConfig(projectPath: string) : Promise<Result<ProjectConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_project_config", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write project config
 */
async writeProjectConfig(projectPath: string, config: ProjectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_project_config", { projectPath, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all saved queries in the project with summary info
 */
async listSavedQueries(projectPath: string) : Promise<Result<QuerySummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_saved_queries", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a saved query file
 */
async getSavedQuery(projectPath: string, filename: string) : Promise<Result<SavedQuery, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_saved_query", { projectPath, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a query file (create or update)
 */
async saveQuery(projectPath: string, filename: string, query: SavedQuery) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_query", { projectPath, filename, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a saved query file
 */
async deleteSavedQuery(projectPath: string, filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_saved_query", { projectPath, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start watching the project config file and env file for changes
 */
async watchProjectConfig(projectPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("watch_project_config", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop watching the project config file
 */
async unwatchProjectConfig() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unwatch_project_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectProjectDb(projectPath: string, connKey: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_project_db", { projectPath, connKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConnectionInfo(connId: string) : Promise<Result<ConnectionInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connection_info", { connId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSqliteObjects(projectPath: string, connKey: string, objectType: string) : Promise<Result<SQLiteObject[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sqlite_objects", { projectPath, connKey, objectType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMongodbCollections(projectPath: string, connKey: string) : Promise<Result<MongoDBCollection[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mongodb_collections", { projectPath, connKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPostgresSchemas(projectPath: string, connKey: string) : Promise<Result<PostgresSchema[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_postgres_schemas", { projectPath, connKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPostgresTables(projectPath: string, connKey: string, schema: string) : Promise<Result<PostgresTable[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_postgres_tables", { projectPath, connKey, schema }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeConnection(projectPath: string, connKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_connection", { projectPath, connKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeProjectConnections(projectPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_project_connections", { projectPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async querySqliteTable(projectPath: string, connKey: string, tableName: string, options: BrowseOptions) : Promise<Result<QueryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_sqlite_table", { projectPath, connKey, tableName, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryPostgresTable(projectPath: string, connKey: string, schema: string, tableName: string, options: BrowseOptions) : Promise<Result<QueryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_postgres_table", { projectPath, connKey, schema, tableName, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryMongodbCollection(projectPath: string, connKey: string, collectionName: string, options: BrowseOptions) : Promise<Result<QueryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_mongodb_collection", { projectPath, connKey, collectionName, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Describe a SQLite table (columns, indexes, foreign keys).
 */
async describeSqliteTable(projectPath: string, connKey: string, tableName: string) : Promise<Result<TableDescription, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("describe_sqlite_table", { projectPath, connKey, tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Describe a PostgreSQL table (columns, indexes, foreign keys,
 * reltuples estimate).
 */
async describePostgresTable(projectPath: string, connKey: string, schema: string, tableName: string) : Promise<Result<TableDescription, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("describe_postgres_table", { projectPath, connKey, schema, tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Describe a MongoDB collection (sampled columns + real indexes +
 * estimated row count).
 */
async describeMongodbCollection(projectPath: string, connKey: string, collectionName: string) : Promise<Result<TableDescription, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("describe_mongodb_collection", { projectPath, connKey, collectionName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a single SQLite row. `pk` must identify exactly one row; we
 * return the number of rows actually changed so the UI can catch the
 * "someone else deleted it between browse and edit" case.
 */
async updateSqliteRow(projectPath: string, connKey: string, tableName: string, pk: Partial<{ [key in string]: JsonValue }>, changes: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_sqlite_row", { projectPath, connKey, tableName, pk, changes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertSqliteRow(projectPath: string, connKey: string, tableName: string, values: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_sqlite_row", { projectPath, connKey, tableName, values }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSqliteRow(projectPath: string, connKey: string, tableName: string, pk: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_sqlite_row", { projectPath, connKey, tableName, pk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostgresRow(projectPath: string, connKey: string, schema: string, tableName: string, pk: Partial<{ [key in string]: JsonValue }>, changes: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_postgres_row", { projectPath, connKey, schema, tableName, pk, changes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertPostgresRow(projectPath: string, connKey: string, schema: string, tableName: string, values: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_postgres_row", { projectPath, connKey, schema, tableName, values }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostgresRow(projectPath: string, connKey: string, schema: string, tableName: string, pk: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_postgres_row", { projectPath, connKey, schema, tableName, pk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMongodbDocument(projectPath: string, connKey: string, collectionName: string, pk: Partial<{ [key in string]: JsonValue }>, changes: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_mongodb_document", { projectPath, connKey, collectionName, pk, changes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertMongodbDocument(projectPath: string, connKey: string, collectionName: string, values: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_mongodb_document", { projectPath, connKey, collectionName, values }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMongodbDocument(projectPath: string, connKey: string, collectionName: string, pk: Partial<{ [key in string]: JsonValue }>) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_mongodb_document", { projectPath, connKey, collectionName, pk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeRawSql(projectPath: string, connKey: string, query: string) : Promise<Result<QueryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_raw_sql", { projectPath, connKey, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeRawMongo(projectPath: string, connKey: string, collection: string, queryType: string, query: string) : Promise<Result<QueryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_raw_mongo", { projectPath, connKey, collection, queryType, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open (or refocus, if already open) a child window.
 */
async openWindow(kind: WindowKind) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_window", { kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Focus the window with the given label. No-op if it does not exist.
 */
async focusWindow(label: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus_window", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close the window with the given label. No-op if it does not exist.
 * Refuses to close the `"main"` label to avoid killing the app.
 */
async closeWindow(label: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Paginated / filtered browse parameters. Consolidated so every engine
 * command takes exactly this type and stays under tauri-specta's
 * 10-argument command limit.
 */
export type BrowseOptions = { limit: number | null; offset: number | null; orderByColumn: string | null; orderByDirection: string | null; 
/**
 * JSON-encoded `Vec<FilterParam>`. Kept as a string (rather than a
 * typed `Vec<FilterParam>`) so the UI's filter DSL can evolve
 * without forcing a binding regen every time. Phase 1 todo 2
 * replaces this with a proper `FilterAst` type.
 */
filters: string | null }
export type ColumnDescription = { name: string; dataType: string; nullable: boolean; default: string | null; isPrimaryKey: boolean; 
/**
 * Ordinal position (1-indexed) in the original CREATE TABLE.
 */
position: number }
export type ColumnInfo = { name: string; data_type: string }
/**
 * Identifies a specific connection inside a project (by the user-visible
 * key from `.based/config.toml`, e.g. `"dev"` or `"prod"`).
 */
export type ConnectionAddress = { project: ProjectAddress; conn_key: string }
export type ConnectionConfig = { label: string | null; engine: Engine; group: string | null; disabled: boolean | null; order: number | null; color: string | null; icon: string | null; file: string | null; readonly: boolean | null; url?: SecretValue | null; host: string | null; port: number | null; database: string | null; username: string | null; password?: SecretValue | null; ssl: boolean | null }
/**
 * A stable identifier for a database connection.
 * Generated from (project_path, conn_key) using a hash function.
 */
export type ConnectionId = string
/**
 * Metadata about a connection stored in the registry.
 */
export type ConnectionInfo = { id: ConnectionId; project_path: string; conn_key: string; engine: Engine; label: string | null }
export type Engine = "sqlite" | "mongodb" | "postgres"
export type ForeignKeyDescription = { name: string | null; columns: string[]; referencedSchema: string | null; referencedTable: string; referencedColumns: string[] }
export type IndexDescription = { name: string; columns: string[]; unique: boolean; primary: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type MongoDBCollection = { name: string }
export type MongoQuery = { type: MongoQueryType; 
/**
 * JSON string for find queries
 */
filter: string | null; 
/**
 * JSON string for aggregation pipeline
 */
pipeline: string | null }
export type MongoQueryType = "find" | "aggregate"
export type PostgresSchema = { name: string }
export type PostgresTable = { name: string; schema: string }
/**
 * Identifies a project on disk. Currently its absolute filesystem path;
 * wrapped so we can swap in a stable ID later without touching callers.
 */
export type ProjectAddress = string
export type ProjectConfig = { version: number; name: string; description: string | null; connection: Partial<{ [key in string]: ConnectionConfig }>; settings: ProjectSettings | null }
export type ProjectSettings = { queryTimeout: number | null; maxResultRows: number | null; enableQueryCache: boolean | null; cacheTTL: number | null }
export type QueryParamType = "string" | "number" | "date" | "boolean" | "select"
export type QueryParameter = { type: QueryParamType; default: JsonValue | null; description: string | null; 
/**
 * Options for select type
 */
options: string[] | null }
/**
 * Result of a data query – rows plus column info plus an optional total
 * row count (for pagination UIs).
 */
export type QueryResult = { columns: ColumnInfo[]; rows: JsonValue[][]; total_count: number | null }
/**
 * Summary info for listing queries (without full content)
 */
export type QuerySummary = { filename: string; name: string; connection: string; description: string | null; tags: string[] | null; favorite: boolean | null }
/**
 * User-visible SQLite object (table, view, index...).
 */
export type SQLiteObject = { name: string }
/**
 * Saved query file (.query.toml) structure
 */
export type SavedQuery = { 
/**
 * Display name
 */
name: string; 
/**
 * Connection key from config.toml
 */
connection: string; 
/**
 * Optional description
 */
description: string | null; 
/**
 * Tags for organization
 */
tags: string[] | null; 
/**
 * Whether this query is favorited
 */
favorite: boolean | null; 
/**
 * Query parameters
 */
params: Partial<{ [key in string]: QueryParameter }> | null; 
/**
 * SQL query (for sqlite, postgres)
 */
sql: SqlQuery | null; 
/**
 * MongoDB query
 */
mongo: MongoQuery | null }
export type SecretValue = { env: string } | { value: string } | { file: string } | string
export type SqlQuery = { query: string }
/**
 * Identifies a workspace tab. The UI can address query tabs, table browse
 * tabs, and pinned inspector tabs uniformly.
 */
export type TabAddress = 
/**
 * A SQL / MongoDB query tab. `id` is a UI-owned identifier (e.g. nanoid).
 */
{ kind: "query"; connection: ConnectionAddress; id: string } | 
/**
 * A table/collection browse tab.
 */
{ kind: "table"; connection: ConnectionAddress; schema: string | null; name: string } | 
/**
 * A schema-inspector tab for a single object.
 */
{ kind: "inspector"; connection: ConnectionAddress; schema: string | null; name: string }
/**
 * Detailed description of a table or collection, rendered by the
 * schema inspector panel.
 */
export type TableDescription = { name: string; 
/**
 * Schema name for Postgres; `None` for SQLite and MongoDB where
 * schemas don't apply.
 */
schema: string | null; 
/**
 * Engine-reported kind: `"table"`, `"view"`, `"collection"`, ...
 */
kind: string; columns: ColumnDescription[]; indexes: IndexDescription[]; foreignKeys: ForeignKeyDescription[]; 
/**
 * Estimated row count when the engine exposes one cheaply; `None`
 * otherwise. We never issue `SELECT COUNT(*)` just to fill this
 * in — the inspector is meant to be fast.
 */
rowCount: number | null }
/**
 * The kinds of windows the app can spawn. Encoded as a tagged enum so
 * the frontend can pattern-match in its router.
 */
export type WindowKind = 
/**
 * Detached workspace tab (query editor or table browser).
 */
{ kind: "tab"; address: TabAddress } | 
/**
 * Pop-out for a query result set.
 */
{ kind: "result_viewer"; title: string } | 
/**
 * App settings window.
 */
{ kind: "settings" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
