// @ts-nocheck
// Auto-generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// Initialize a new Based project in the given directory
	initializeProject: (projectPath: string) => typedError<null, string>(__TAURI_INVOKE("initialize_project", { projectPath })),
	/**
	 *  Create a turnkey sample project at `{parent_dir}/{name}`.
	 * 
	 *  Spins up a SQLite database seeded with a tiny users/posts/comments
	 *  schema so new users can immediately browse, filter, run joins, and
	 *  try EXPLAIN on realistic-shaped data without first standing up
	 *  their own database.
	 * 
	 *  Returns the absolute path of the newly-created project so the
	 *  frontend can open it straight away.
	 */
	createSampleProject: (parentDir: string, name: string) => typedError<string, string>(__TAURI_INVOKE("create_sample_project", { parentDir, name })),
	// Read and parse project config
	readProjectConfig: (projectPath: string) => typedError<ProjectConfig, string>(__TAURI_INVOKE("read_project_config", { projectPath })),
	// Write project config
	writeProjectConfig: (projectPath: string, config: ProjectConfig) => typedError<null, string>(__TAURI_INVOKE("write_project_config", { projectPath, config })),
	// List all saved queries in the project with summary info
	listSavedQueries: (projectPath: string) => typedError<QuerySummary[], string>(__TAURI_INVOKE("list_saved_queries", { projectPath })),
	// Read a saved query file
	getSavedQuery: (projectPath: string, filename: string) => typedError<SavedQuery, string>(__TAURI_INVOKE("get_saved_query", { projectPath, filename })),
	// Save a query file (create or update)
	saveQuery: (projectPath: string, filename: string, query: SavedQuery) => typedError<null, string>(__TAURI_INVOKE("save_query", { projectPath, filename, query })),
	// Delete a saved query file
	deleteSavedQuery: (projectPath: string, filename: string) => typedError<null, string>(__TAURI_INVOKE("delete_saved_query", { projectPath, filename })),
	// Start watching the project config file and env file for changes
	watchProjectConfig: (projectPath: string) => typedError<null, string>(__TAURI_INVOKE("watch_project_config", { projectPath })),
	// Stop watching the project config file
	unwatchProjectConfig: () => typedError<null, string>(__TAURI_INVOKE("unwatch_project_config")),
	connectProjectDb: (projectPath: string, connKey: string) => typedError<string, string>(__TAURI_INVOKE("connect_project_db", { projectPath, connKey })),
	/**
	 *  Probe a connection config without registering it anywhere.
	 * 
	 *  The connection wizard uses this for its "Test connection" button
	 *  so the user gets immediate feedback before committing the config
	 *  to `config.toml`. We intentionally do not cache or pool the
	 *  resulting connection: the probe runs, we drop the pool, and a
	 *  subsequent regular `connect_project_db` re-establishes a pool we
	 *  actually track.
	 */
	testConnection: (projectPath: string, connConfig: ConnectionConfig) => typedError<null, string>(__TAURI_INVOKE("test_connection", { projectPath, connConfig })),
	getConnectionInfo: (connId: string) => typedError<ConnectionInfo, string>(__TAURI_INVOKE("get_connection_info", { connId })),
	getSqliteObjects: (projectPath: string, connKey: string, objectType: string) => typedError<SQLiteObject[], string>(__TAURI_INVOKE("get_sqlite_objects", { projectPath, connKey, objectType })),
	getMongodbCollections: (projectPath: string, connKey: string) => typedError<MongoDBCollection[], string>(__TAURI_INVOKE("get_mongodb_collections", { projectPath, connKey })),
	getPostgresSchemas: (projectPath: string, connKey: string) => typedError<PostgresSchema[], string>(__TAURI_INVOKE("get_postgres_schemas", { projectPath, connKey })),
	getPostgresTables: (projectPath: string, connKey: string, schema: string) => typedError<PostgresTable[], string>(__TAURI_INVOKE("get_postgres_tables", { projectPath, connKey, schema })),
	closeConnection: (projectPath: string, connKey: string) => typedError<null, string>(__TAURI_INVOKE("close_connection", { projectPath, connKey })),
	closeProjectConnections: (projectPath: string) => typedError<null, string>(__TAURI_INVOKE("close_project_connections", { projectPath })),
	querySqliteTable: (projectPath: string, connKey: string, tableName: string, options: BrowseOptions) => typedError<QueryResult, string>(__TAURI_INVOKE("query_sqlite_table", { projectPath, connKey, tableName, options })),
	queryPostgresTable: (projectPath: string, connKey: string, schema: string, tableName: string, options: BrowseOptions) => typedError<QueryResult, string>(__TAURI_INVOKE("query_postgres_table", { projectPath, connKey, schema, tableName, options })),
	queryMongodbCollection: (projectPath: string, connKey: string, collectionName: string, options: BrowseOptions) => typedError<QueryResult, string>(__TAURI_INVOKE("query_mongodb_collection", { projectPath, connKey, collectionName, options })),
	// Describe a SQLite table (columns, indexes, foreign keys).
	describeSqliteTable: (projectPath: string, connKey: string, tableName: string) => typedError<TableDescription, string>(__TAURI_INVOKE("describe_sqlite_table", { projectPath, connKey, tableName })),
	/**
	 *  Describe a PostgreSQL table (columns, indexes, foreign keys,
	 *  reltuples estimate).
	 */
	describePostgresTable: (projectPath: string, connKey: string, schema: string, tableName: string) => typedError<TableDescription, string>(__TAURI_INVOKE("describe_postgres_table", { projectPath, connKey, schema, tableName })),
	/**
	 *  Describe a MongoDB collection (sampled columns + real indexes +
	 *  estimated row count).
	 */
	describeMongodbCollection: (projectPath: string, connKey: string, collectionName: string) => typedError<TableDescription, string>(__TAURI_INVOKE("describe_mongodb_collection", { projectPath, connKey, collectionName })),
	/**
	 *  Update a single SQLite row. `pk` must identify exactly one row; we
	 *  return the number of rows actually changed so the UI can catch the
	 *  "someone else deleted it between browse and edit" case.
	 */
	updateSqliteRow: (projectPath: string, connKey: string, tableName: string, pk: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }, changes: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("update_sqlite_row", { projectPath, connKey, tableName, pk, changes })),
	insertSqliteRow: (projectPath: string, connKey: string, tableName: string, values: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("insert_sqlite_row", { projectPath, connKey, tableName, values })),
	deleteSqliteRow: (projectPath: string, connKey: string, tableName: string, pk: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("delete_sqlite_row", { projectPath, connKey, tableName, pk })),
	updatePostgresRow: (projectPath: string, connKey: string, schema: string, tableName: string, pk: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }, changes: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("update_postgres_row", { projectPath, connKey, schema, tableName, pk, changes })),
	insertPostgresRow: (projectPath: string, connKey: string, schema: string, tableName: string, values: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("insert_postgres_row", { projectPath, connKey, schema, tableName, values })),
	deletePostgresRow: (projectPath: string, connKey: string, schema: string, tableName: string, pk: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("delete_postgres_row", { projectPath, connKey, schema, tableName, pk })),
	updateMongodbDocument: (projectPath: string, connKey: string, collectionName: string, pk: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }, changes: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("update_mongodb_document", { projectPath, connKey, collectionName, pk, changes })),
	insertMongodbDocument: (projectPath: string, connKey: string, collectionName: string, values: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("insert_mongodb_document", { projectPath, connKey, collectionName, values })),
	deleteMongodbDocument: (projectPath: string, connKey: string, collectionName: string, pk: { [key in string]: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: Map<string, Value> }) & { Array?: never; Bool?: never; Number?: never; String?: never } }) => typedError<number, string>(__TAURI_INVOKE("delete_mongodb_document", { projectPath, connKey, collectionName, pk })),
	executeRawSql: (projectPath: string, connKey: string, query: string, token: string | null, timeoutMs: number | null) => typedError<QueryResult, string>(__TAURI_INVOKE("execute_raw_sql", { projectPath, connKey, query, token, timeoutMs })),
	executeRawMongo: (projectPath: string, connKey: string, collection: string, queryType: string, query: string, token: string | null, timeoutMs: number | null) => typedError<QueryResult, string>(__TAURI_INVOKE("execute_raw_mongo", { projectPath, connKey, collection, queryType, query, token, timeoutMs })),
	/**
	 *  Cancel an in-flight query by token. The actual mid-query checks
	 *  land with the Phase 2 "params + history + cancel" work; this
	 *  command is wired up now so the frontend can start carrying the
	 *  token round-trip through the editor.
	 */
	cancelQuery: (token: string) => typedError<boolean, string>(__TAURI_INVOKE("cancel_query", { token })),
	// Open (or refocus, if already open) a child window.
	openWindow: (kind: WindowKind) => typedError<string, string>(__TAURI_INVOKE("open_window", { kind })),
	// Focus the window with the given label. No-op if it does not exist.
	focusWindow: (label: string) => typedError<null, string>(__TAURI_INVOKE("focus_window", { label })),
	/**
	 *  Close the window with the given label. No-op if it does not exist.
	 *  Refuses to close the `"main"` label to avoid killing the app.
	 */
	closeWindow: (label: string) => typedError<null, string>(__TAURI_INVOKE("close_window", { label })),
};

/* Types */
/**
 *  Paginated / filtered browse parameters. Consolidated so every engine
 *  command takes exactly this type and stays under tauri-specta's
 *  10-argument command limit.
 */
export type BrowseOptions = {
	limit: number | null,
	offset: number | null,
	orderByColumn: string | null,
	orderByDirection: string | null,
	/**
	 *  JSON-encoded `Vec<FilterParam>`. Kept as a string (rather than a
	 *  typed `Vec<FilterParam>`) so the UI's filter DSL can evolve
	 *  without forcing a binding regen every time. Phase 1 todo 2
	 *  replaces this with a proper `FilterAst` type.
	 */
	filters: string | null,
};

export type ColumnDescription = {
	name: string,
	dataType: string,
	nullable: boolean,
	default: string | null,
	isPrimaryKey: boolean,
	// Ordinal position (1-indexed) in the original CREATE TABLE.
	position: number,
};

export type ColumnInfo = {
	name: string,
	data_type: string,
};

/**
 *  Identifies a specific connection inside a project (by the user-visible
 *  key from `.based/config.toml`, e.g. `"dev"` or `"prod"`).
 */
export type ConnectionAddress = {
	project: ProjectAddress,
	conn_key: string,
};

export type ConnectionConfig = {
	label: string | null,
	engine: Engine,
	group: string | null,
	disabled: boolean | null,
	order: number | null,
	color: string | null,
	icon: string | null,
	file: string | null,
	readonly: boolean | null,
	url: SecretValue | null,
	host: string | null,
	port: number | null,
	database: string | null,
	username: string | null,
	password: SecretValue | null,
	ssl: boolean | null,
};

/**
 *  A stable identifier for a database connection.
 *  Generated from (project_path, conn_key) using a hash function.
 */
export type ConnectionId = string;

// Metadata about a connection stored in the registry.
export type ConnectionInfo = {
	id: ConnectionId,
	project_path: string,
	conn_key: string,
	engine: Engine,
	label: string | null,
};

export type Engine = "sqlite" | "mongodb" | "postgres";

export type ForeignKeyDescription = {
	name: string | null,
	columns: string[],
	referencedSchema: string | null,
	referencedTable: string,
	referencedColumns: string[],
};

export type IndexDescription = {
	name: string,
	columns: string[],
	unique: boolean,
	primary: boolean,
};

export type MongoDBCollection = {
	name: string,
};

export type MongoQuery = {
	type: MongoQueryType,
	// JSON string for find queries
	filter: string | null,
	// JSON string for aggregation pipeline
	pipeline: string | null,
};

export type MongoQueryType = "find" | "aggregate";

export type PostgresSchema = {
	name: string,
};

export type PostgresTable = {
	name: string,
	schema: string,
};

/**
 *  Identifies a project on disk. Currently its absolute filesystem path;
 *  wrapped so we can swap in a stable ID later without touching callers.
 */
export type ProjectAddress = string;

export type ProjectConfig = {
	version: number,
	name: string,
	description: string | null,
	connection: { [key in string]: ConnectionConfig },
	settings: ProjectSettings | null,
};

export type ProjectSettings = {
	queryTimeout: number | null,
	maxResultRows: number | null,
	enableQueryCache: boolean | null,
	cacheTTL: number | null,
};

export type QueryParamType = "string" | "number" | "date" | "boolean" | "select";

export type QueryParameter = {
	type: QueryParamType,
	default: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never } | null,
	description: string | null,
	// Options for select type
	options: string[] | null,
};

/**
 *  Result of a data query – rows plus column info plus an optional total
 *  row count (for pagination UIs).
 */
export type QueryResult = {
	columns: ColumnInfo[],
	rows: (("Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Vec<Value> }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never })[])[],
	total_count: number | null,
};

// Summary info for listing queries (without full content)
export type QuerySummary = {
	filename: string,
	name: string,
	connection: string,
	description: string | null,
	tags: string[] | null,
	favorite: boolean | null,
};

// User-visible SQLite object (table, view, index...).
export type SQLiteObject = {
	name: string,
};

// Saved query file (.query.toml) structure
export type SavedQuery = {
	// Display name
	name: string,
	// Connection key from config.toml
	connection: string,
	// Optional description
	description: string | null,
	// Tags for organization
	tags: string[] | null,
	// Whether this query is favorited
	favorite: boolean | null,
	// Query parameters
	params: { [key in string]: QueryParameter } | null,
	// SQL query (for sqlite, postgres)
	sql: SqlQuery | null,
	// MongoDB query
	mongo: MongoQuery | null,
};

export type SecretValue = ({ env: string }) & { file?: never; value?: never } | ({ value: string }) & { env?: never; file?: never } | ({ file: string }) & { env?: never; value?: never } | string;

export type SqlQuery = {
	query: string,
};

/**
 *  Identifies a workspace tab. The UI can address query tabs, table browse
 *  tabs, and pinned inspector tabs uniformly.
 */
export type TabAddress = 
// A SQL / MongoDB query tab. `id` is a UI-owned identifier (e.g. nanoid).
{ kind: "query"; connection: ConnectionAddress; id: string } | 
// A table/collection browse tab.
{ kind: "table"; connection: ConnectionAddress; schema: string | null; name: string } | 
// A schema-inspector tab for a single object.
{ kind: "inspector"; connection: ConnectionAddress; schema: string | null; name: string };

/**
 *  Detailed description of a table or collection, rendered by the
 *  schema inspector panel.
 */
export type TableDescription = {
	name: string,
	/**
	 *  Schema name for Postgres; `None` for SQLite and MongoDB where
	 *  schemas don't apply.
	 */
	schema: string | null,
	// Engine-reported kind: `"table"`, `"view"`, `"collection"`, ...
	kind: string,
	columns: ColumnDescription[],
	indexes: IndexDescription[],
	foreignKeys: ForeignKeyDescription[],
	/**
	 *  Estimated row count when the engine exposes one cheaply; `None`
	 *  otherwise. We never issue `SELECT COUNT(*)` just to fill this
	 *  in — the inspector is meant to be fast.
	 */
	rowCount: number | null,
};

/**
 *  The kinds of windows the app can spawn. Encoded as a tagged enum so
 *  the frontend can pattern-match in its router.
 */
export type WindowKind = 
// Detached workspace tab (query editor or table browser).
{ kind: "tab"; address: TabAddress } | 
// Pop-out for a query result set.
{ kind: "result_viewer"; title: string } | 
// App settings window.
{ kind: "settings" };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

