/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId/index'
import { Route as ProjectProjectIdConnConnKeyRouteImport } from './routes/project.$projectId/conn.$connKey'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdConnConnKeyRoute =
  ProjectProjectIdConnConnKeyRouteImport.update({
    id: '/conn/$connKey',
    path: '/conn/$connKey',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/conn/$connKey': typeof ProjectProjectIdConnConnKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/conn/$connKey': typeof ProjectProjectIdConnConnKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/conn/$connKey': typeof ProjectProjectIdConnConnKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/project/$projectId'
    | '/project/$projectId/'
    | '/project/$projectId/conn/$connKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/project/$projectId'
    | '/project/$projectId/conn/$connKey'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/project/$projectId'
    | '/project/$projectId/'
    | '/project/$projectId/conn/$connKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/conn/$connKey': {
      id: '/project/$projectId/conn/$connKey'
      path: '/conn/$connKey'
      fullPath: '/project/$projectId/conn/$connKey'
      preLoaderRoute: typeof ProjectProjectIdConnConnKeyRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdConnConnKeyRoute: typeof ProjectProjectIdConnConnKeyRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdConnConnKeyRoute: ProjectProjectIdConnConnKeyRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
