version = 1
name = "based"
description = "A new Based project"

[connection.northwind]
label = "Northwind Database"
engine = "sqlite"
group = "local"
file = "/Users/pavi2410/Downloads/northwind.db"

[connection.test_mongo]
label = "Test MongoDB"
engine = "mongodb"
group = "remote"
url = { env = "MONGO_URL" }

[connection.railway_pg]
label = "Railway PostgreSQL"
engine = "postgres"
group = "remote"
host = "caboose.proxy.rlwy.net"
port = 34306
database = "railway"
username = "postgres"
password = "UYDGdVvqPgJhIwndpIxkWrpffspaXBVT"
ssl = true

[settings]
queryTimeout = 30000
maxResultRows = 1000
enableQueryCache = true
cacheTTL = 3600
