name = "List Postgres Tables"
connection = "railway_pg"
favorite = false

[sql]
query = """
SELECT table_name as name, table_schema as schema
FROM information_schema.tables
WHERE table_type = 'BASE TABLE'
ORDER BY table_name;"""
