name = "Base Collection Count"
connection = "watertap_edb"
description = "Total documents in the base collection"
tags = ["meta"]

[aggregate]
collection = "base"
pipeline = """
[
  { "$count": "total" }
]
"""
